### ISSUE TITLE
Notifications error

### ISSUE THREAD

**Issue by deeks01** [JulianRunnels/Bitwarden_Self_Host#12]
Hi Julian,

I managed to get DockerRS working nicely. One thing I noticed that de mobile app doesn't sync with my webbrowser properly. I need to manually force the app to sync.
Upon investigation i found  the error below in the Bitwarden container.

[2021-03-13 14:43:47.512][bitwarden_rs::api::notifications][ERROR] 
    ###########################################################
    '/notifications/hub' should be proxied to the websocket server or notifications won't work.
    Go to the Wiki for more info, or disable WebSockets setting WEBSOCKET_ENABLED=false.
    ###########################################################################################

How can I fix this? I pretty much used your docker-compose config. 

Cheers, 
Deeks

**Comment by JulianRunnels** [comment]
Hmm @deeks01 interesting find, the app has been working fine for me overall, but happy to look into this. I will take a look later tonight.

**Comment by JulianRunnels** [comment]
@deeks01 Apologies on the delay, some real life stuff came up last night. I reviewed the bitwarden_rs wiki (the underlying container that creates this project) and unfortunately, it doesn't look like bitwarden_rs supports notifications to mobile apps. Specifically this page [here](https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-WebSocket-notifications) says:

> Note that WebSocket notifications are not applicable to the mobile (Android/iOS) Bitwarden clients. These clients use the native push notification service instead (FCM for Android, APNs for iOS). bitwarden_rs does not currently support push notifications to mobile clients.

It looks like this exact issue was discussed in issue [126](https://github.com/dani-garcia/bitwarden_rs/issues/126).

That being said, it should be possible to enable web sockets on the desktop portion at the very least for my setup, I will review further. For your ask, unfortunately it looks like you will have to continue to manually sync the apps, at least while using the bitwarden_rs solution.

**Comment by JulianRunnels** [comment]
@deeks01 I wish I could solve the mobile push notifications, but until an update is made in the bitwarden_rs platform I can't help there. In the meantime I have set up and push a change to enable web sockets for desktop applications upon initial setup!

**Comment by deeks01** [comment]
Hi Julian,

Thanks for looking into this, much appreciated!

Deeks01
