### ISSUE TITLE
Apple rejects certificates with validatity longer than 398 days 

### ISSUE THREAD

**Issue by bez820** [JulianRunnels/Bitwarden_Self_Host#19]
I've been using your excellent repo for couple of years now. Thanks for all your hard work.

I've completed a new reinstall, with your most recent changes that included the bitwarden certificate validity increases #18 .
This works fine on most devices, but unfortunately not on IOS devices, due to Apple treating the certificate as untrusted.

[Apple tighten things back in 2020](https://support.apple.com/en-us/HT211025) by only trusting certificates issued after 01/09/2020 with validity date less than 398 days.

https://github.com/JulianRunnels/Bitwarden_Self_Host/blob/641139832b439e05acd8f9584efc26dedc621f03/create_ssl.sh#L42

Had to revert this line back to 375 days, then all devices including IOS where working again.

**Comment by JulianRunnels** [comment]
Ah well you just solved the issue that I ran into today. That's a bit of a bummer, but understandable. I'll move the creation time back to 375. WIth the revoke and creation, it should be easy to recreate a new cert each year. Appreciate reaching out.

**Comment by JulianRunnels** [comment]
Changes merged back to 1 year certificate
