### ISSUE TITLE
Connect Domain

### ISSUE THREAD

**Issue by LcsTh0** [JulianRunnels/Bitwarden_Self_Host#2]
I have set everything successfully and have set up my domain to the IP where everything is set up but I just get the Welcome to nginx! page.

**Comment by JulianRunnels** [comment]
Hey @LcsTh0, can you run `sudo docker-compose up` without the -d which should print out more information, and copy the output, or a redacted version of your docker-compose file?

It sounds like your Bitwarden instance didn't start correctly, since your are reaching Nginx but not the actual vault.

**Comment by LcsTh0** [comment]
Do you mean that?

Creating bitwarden_self_host_nginx_1     ... done
Creating bitwarden_self_host_bitwarden_1 ... done
Creating bw_backup                       ... done
Attaching to bitwarden_self_host_bitwarden_1, bitwarden_self_host_nginx_1, bw_ba                                                                                                             ckup
bitwarden_1  | /----------------------------------------------------------------                                                                                                             ----\
bitwarden_1  | |                       Starting Bitwarden_RS                                                                                                                                     |
bitwarden_1  | |                           Version 1.17.0                                                                                                                                        |
bitwarden_1  | |----------------------------------------------------------------                                                                                                             ----|
bitwarden_1  | | This is an *unofficial* Bitwarden implementation, DO NOT use th                                                                                                             e   |
bitwarden_1  | | official channels to report bugs/features, regardless of client                                                                                                             .   |
bitwarden_1  | | Send usage/configuration questions or feature requests to:                                                                                                                      |
bitwarden_1  | |   https://bitwardenrs.discourse.group/                                                                                                                                          |
bitwarden_1  | | Report suspected bugs/issues in the software itself at:                                                                                                                         |
bitwarden_1  | |   https://github.com/dani-garcia/bitwarden_rs/issues/new                                                                                                                        |
bitwarden_1  | \----------------------------------------------------------------                                                                                                             ----/
bitwarden_1  |
bitwarden_1  | [WARNING] The following environment variables are being overriden                                                                                                              by the config file,
bitwarden_1  | [WARNING] please use the admin panel to make changes to them:
bitwarden_1  | [WARNING] DOMAIN, ADMIN_TOKEN
bitwarden_1  |
bitwarden_1  | [2020-11-11 17:14:45.523][start][INFO] Rocket has launched from h                                                                                                             ttp://0.0.0.0:80
bitwarden_1  | [2020-11-11 17:14:45.523][ws][INFO] Listening for new connections                                                                                                              on 0.0.0.0:3012.
bw_backup    | Running entrypoint.sh as uid=0(root) gid=0(root) groups=0(root),1                                                                                                             (bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),                                                                                                             27(video)
bw_backup    | Initalizing...
bw_backup    | Writing backup command "/sbin/su-exec 0:0 /app/backup.sh" to cron                                                                                                             .
bw_backup    | Restarting entrypoint.sh as app:app
bw_backup    | Running entrypoint.sh as uid=100(app) gid=101(app) groups=101(app                                                                                                             )
bw_backup    | ==> /app/log/backup.log <==
bw_backup    | 2020-11-11 18:14:45 - Container started
bw_backup    |
bw_backup    | ==> /app/log/cron.log <==
bw_backup    | crond: crond (busybox 1.31.1) started, log level 8
