### ISSUE TITLE
question about the FQDN

### ISSUE THREAD

**Issue by carmolim** [JulianRunnels/Bitwarden_Self_Host#26]
Hello I just finish to run the docker-compose and everything went ok. I can access the vaultwarden using the browser entering the machine IP with https. But to use the FQDN that I inserted when I ran the `create_ssl.sh` I need to edit the /etc/hosts on my machine, but that way I can't the bitward client on iOS, what I'm missing?

**Comment by JulianRunnels** [comment]
There are 2 options:
1. If you have a PiHole or other internal DNS server, set the FQDN there.
2. Make sure the hostname of the host server is the same as the FQDN. Most LANs will automatically associate hostnames with a *.lan or *.local endpoint.

If you have the vault on a host named Vault, you should be able to reach it at https://vault.lan or https://vault.local. 

You can test this by pinging the hostname from another machine and seeing what it provides back.

**Comment by carmolim** [comment]
Thanks! I thing that will be easier to setup a Local DNS Records on pihole.
