### ISSUE TITLE
NGINX container not restarting upon reboot

### ISSUE THREAD

**Issue by digilink** [JulianRunnels/Bitwarden_Self_Host#6]
Hello, 
     I have cloned this repository and used setup.sh to deploy the bitwarden-rs, backup, and NGINX containers. All appeared to go well, however the NGINX container is not restarting upon a reboot, and I am not sure if this is by design or missing feature in the docker compose file. 

I tried adding restart: always to the NGINX definition and re-ran sudo docker-compose up -d, it did appear to help as the NGINX container restarted upon reboot and is running as expected. 

I wanted to raise the issue as I am unsure of the desired behavior and don't want to make any assumptions. I could see this option maybe omitted due to having an external NGINX or other proxy perhaps? Was that the intent, or is something missing and/or broken?

**Comment by JulianRunnels** [comment]
@digilink Thanks for the notice, you are correct that was not intended. I have updated the docker-compose.yml file and will merge the change now.

**Comment by JulianRunnels** [comment]
File has been updated and merged, closing issue!
