### ISSUE TITLE
Error on android APP

### ISSUE THREAD

**Issue by ebanDev** [JulianRunnels/Bitwarden_Self_Host#8]
Hi, thank you for this super cool script ! Hi have this error on the android app when I try to log in `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.` I've converted the certificate to a DER file with the command `sudo openssl x509 -outform der -in myCA.crt -out myCA_der.crt` and installed it on my phone. I'm running Android 10 (LineageOS 17.1)

**Comment by JulianRunnels** [comment]
Hey @ebanDev, not sure if you need to change the .crt file format to der, the outputted one works for me on Android. Make sure that you've moved the myCA.crt over and installed it as a CA, which I believe is Settings -> Security -> Encryption & credentials -> CA Certificate on Android.

Go to the Vault endpoint https://vault-hostname and double check that the cert in place there is the one you created under the custom CA.

As far as I can tell, that error just means that there is either an issue with the cert on the server side or the CA you installed on your client side. You can verify the CA installed under  Settings -> Security -> Encryption & credentials -> Trusted Credentials -> User.

**Comment by ebanDev** [comment]
Hey thank you for your quick answer :), I can confirm that the cert in place is my created under my custom CA. I've installed the CA on my phone so I don't really know where is the problem :/

**Comment by ebanDev** [comment]
![Screenshot_20210226-121356_Param�tres](https://user-images.githubusercontent.com/57091497/109293548-3bacb300-782c-11eb-8f23-f5abb1c8635d.png)
![Screenshot_20210226-121349_Param�tres](https://user-images.githubusercontent.com/57091497/109293550-3d767680-782c-11eb-8f2a-fb36ee5be349.png)

**Comment by ebanDev** [comment]
Finally I found, I followed this tutorial https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome and it seems to work !

**Comment by JulianRunnels** [comment]
Awesome, glad its working. Looking at what you posted, the only difference I can see is the dataEncipherment piece in the keyUsage 

Article:
```
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, **dataEncipherment**
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = bitwarden.local
DNS.2 = www.bitwarden.local
```

Mine:
```
[ server_cert ]
# Extensions for server certificates (`man x509v3_config`).
basicConstraints = CA:FALSE
nsCertType = server
nsComment = "OpenSSL Generated Server Certificate"
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer:always
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @my_subject_alt_names
```

I will add that piece in and hopefully that might fix it for other people, though its weird because I can access Chrome on Android with the cert that is created normally.

**Comment by JulianRunnels** [comment]
Closing issue now due to change

**Comment by ebanDev** [comment]
I think the difference is that they say `Add the root certificate and the bitwarden certificate to client computers.`, maybe you should specify to make a p12 with the bitwarden certificate
